import re

from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer
)

from reportlab.lib.styles import getSampleStyleSheet


def generate_pdf(review_result):

    pdf_file = "code_review_report.pdf"

    doc = SimpleDocTemplate(pdf_file)

    styles = getSampleStyleSheet()

    review_result = review_result.replace("\n", "<br/>")

    content = [
        Paragraph("AI Code Review Report", styles['Title']),
        Spacer(1, 12),
        Paragraph(review_result, styles['BodyText'])
    ]

    doc.build(content)

    return pdf_file


def extract_score(review_text):
    """
    Extract Code Quality Score.

    Example:
    Code Quality Score: 8.5/10
    """

    pattern = r"Code Quality Score\s*[:|-]\s*(\d+(\.\d+)?)"

    match = re.search(
        pattern,
        review_text,
        re.IGNORECASE
    )

    if match:
        return float(match.group(1))

    return None



def extract_fixed_code(review_text):
    """
    Extract code block from markdown response.
    """

    pattern = r"```(?:\w+)?\n(.*?)```"

    match = re.search(
        pattern,
        review_text,
        re.DOTALL
    )

    if match:
        return match.group(1).strip()

    return ""


def extract_severity(review_text):
    """
    Extract severity levels from response.
    """

    severity_levels = [
        "Critical",
        "High",
        "Medium",
        "Low"
    ]

    found = []

    for level in severity_levels:
        if level.lower() in review_text.lower():
            found.append(level)

    return found


def clean_response(review_text):
    """
    Remove unwanted spaces.
    """

    return review_text.strip()


def format_for_pdf(
    code,
    language,
    review_text
):
    """
    Create formatted report content.
    """

    return f"""
AI CODE REVIEW REPORT

Language:
{language}

--------------------------------------------------

Submitted Code:

{code}

--------------------------------------------------

Review Result:

{review_text}

--------------------------------------------------

Generated By:
AI Code Reviewer
"""